### ISSUE TITLE
Bug in isce for large data sets?

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#106]
Below the error I get repeatedly with an India data set. It complains about a missing log file although the file `isce.log.1` seems to be there.  Did anybody see this?  It is not related to any particular dataset. A job with a particular file works fine one time but then it fails.  

```
/login3/projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files[1042] cat stderr_files/run_5_pairs_misreg_10_19933186.e
--- Logging error ---
Traceback (most recent call last):
  File "/nethome/famelung/test/test1/rsmas_insar/3rdparty/miniconda3/lib/python3.6/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/nethome/famelung/test/test1/rsmas_insar/3rdparty/miniconda3/lib/python3.6/logging/handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/nethome/famelung/test/test1/rsmas_insar/3rdparty/miniconda3/lib/python3.6/logging/handlers.py", line 113, in rotate
    os.rename(source, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.1'
Call stack:
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/SentinelWrapper.py", line 252, in <module>
    main(args.start,args.end)
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/SentinelWrapper.py", line 243, in main
    cfgParser.runCmd()
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/SentinelWrapper.py", line 53, in runCmd
    func_modules.main(self.funcParams[section])
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/overlap_withDEM.py", line 360, in main
    multCor = createCoherence(multIntName)
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/overlap_withDEM.py", line 224, in createCoherence
    inimg = IML.mmapFromISCE(intfile + '.xml', logging)
  File "/nethome/famelung/test/test1/rsmas_insar/3rdparty/isce/ISCE/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 469, in mmapFromISCE
    'dtype = %s \n'%(img.dataType))
Message: 'Creating readonly ISCE mmap with \nfile = /projects/scratch/insarlab/famelung/NorthIndiaSenDT34/ESD/20170302_20170326/IW2/overlap_14.5alks_15rlks.int \nbands = 1 \nwidth = 1673 \nlength = 23 \nscheme = BIP \ndtype = CFLOAT \n'
Arguments: ()
```
Here the isce.log* files. They are there:
```
//login3/projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files[1040] ll isce.log*
-rw-rw--w-+ 1 famelung insarlab 39549 Mar 23 20:13 isce.log
-rw-rw--w-+ 1 famelung insarlab 39549 Mar 23 20:13 isce.log.1
-rw-rw--w-+ 1 famelung insarlab 39549 Mar 23 20:02 isce.log.2
-rw-rw--w-+ 1 famelung insarlab 39549 Mar 23 20:00 isce.log.3
-rw-rw--w-+ 1 famelung insarlab 31749 Mar 23 19:40 isce.log.4
-rw-rw--w-+ 1 famelung insarlab 31749 Mar 23 19:40 isce.log.5
```
As I said, I see this repeatedly:
```
//login3/projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files[1043] grep FileNotFoundError  stderr_files/run_5_pairs_misreg_?_*.e
stderr_files/run_5_pairs_misreg_6_19933182.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.5'
stderr_files/run_5_pairs_misreg_7_19933183.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.4' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.5'
stderr_files/run_5_pairs_misreg_8_19933184.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.3' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.4'
stderr_files/run_5_pairs_misreg_9_19933185.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.4' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.5'
//login3/projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files[1045] grep FileNotFoundError  stderr_files/run_5_pairs_misreg_1?_*.e
stderr_files/run_5_pairs_misreg_10_19933186.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.1'
stderr_files/run_5_pairs_misreg_17_19933193.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.3' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.4'
stderr_files/run_5_pairs_misreg_18_19929429.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.5'
stderr_files/run_5_pairs_misreg_18_19933194.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.3' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.4'
stderr_files/run_5_pairs_misreg_19_19933195.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.3' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.4'
```

**Comment by falkamelung** [comment]
The first step is to detect when an error occurs and to raise an exception. `create_batch.py` currently does not complain when a job fails. So we should create functions to check for errors to be run at the end of `create_batch`. The first function would raise an exception is the string 'Successfully completed' is not found in all *.o files.  The second function would raise an exception if 'exit code 137' is found. `createBatch.pl` had this functionality but this was not ported to `create_batch.py` yet. 

Any thoughts? 

Where should it go in `create_batch.py`, at the end of `submit_batch_jobs` or in the `main` function after the `submit_batch_jobs` call?

Does anybody has time to do this? If not I may do this first thing after Galapagos, so feedback is very welcome.

```
exit_if_string_not_found_in_stdout('Successfully completed`)
exit_if_string_found_in_stdout('Exited with exit code 137')
exit_if_string_found_in_stderr('Traceback (most recent call last)')
```
Background:
Here an example for a stdout that was successful although an error occurred.
```
//login4/projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files[1045] ^30^40
head -40 run_5_pairs_misreg_6_20078806.o
Sender: LSF System <lsfadmin@n267>
Subject: Job 20078806: <run_5_pairs_misreg_6> in cluster <mk2> Done

Job <run_5_pairs_misreg_6> was submitted from host <n313> by user <famelung> in cluster <mk2>.
Job was executed on host(s) <n267>, in queue <general>, as user <famelung> in cluster <mk2>.
</nethome/famelung> was used as the home directory.
</scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files> was used as the working directory.
Started at Sat Mar 30 04:42:33 2019
Results reported on Sat Mar 30 05:15:46 2019

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#! /bin/tcsh
#BSUB -J run_5_pairs_misreg_6
#BSUB -P insarlab
#BSUB -n 1
#BSUB -R span[hosts=1]
#BSUB -o run_5_pairs_misreg_6_%J.o
#BSUB -e run_5_pairs_misreg_6_%J.e
#BSUB -q general
#BSUB -W 7:00
#BSUB -R rusage[mem=3700]
free
cd /projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files
SentinelWrapper.py -c /projects/scratch/insarlab/famelung/NorthIndiaSenDT34/configs/config_misreg_20170302_20170314


------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time :                                   2666.24 sec.
    Max Memory :                                 1831 MB
    Average Memory :                             1340.99 MB
    Total Requested Memory :                     3700.00 MB
    Delta Memory :                               1869.00 MB
```
Here the corresponding *.e file. Why did it not fail although there was an exception? (still running to check whether it was fatal).
```
//login4/projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files[1040] cat run_5_pairs_misreg_6_20078806.e
--- Logging error ---
Traceback (most recent call last):
  File "/nethome/famelung/test/test1/rsmas_insar/3rdparty/miniconda3/lib/python3.6/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/nethome/famelung/test/test1/rsmas_insar/3rdparty/miniconda3/lib/python3.6/logging/handlers.py", line 169, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.2' -> '/scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files/isce.log.3'
Call stack:
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/SentinelWrapper.py", line 252, in <module>
    main(args.start,args.end)
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/SentinelWrapper.py", line 243, in main
    cfgParser.runCmd()
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/SentinelWrapper.py", line 53, in runCmd
    func_modules.main(self.funcParams[section])
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/overlap_withDEM.py", line 360, in main
    multCor = createCoherence(multIntName)
  File "/nethome/famelung/test/test1/rsmas_insar/sources/isceStack/sentinelstack/overlap_withDEM.py", line 224, in createCoherence
    inimg = IML.mmapFromISCE(intfile + '.xml', logging)
  File "/nethome/famelung/test/test1/rsmas_insar/3rdparty/isce/ISCE/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 469, in mmapFromISCE
    'dtype = %s \n'%(img.dataType))
Message: 'Creating readonly ISCE mmap with \nfile = /projects/scratch/insarlab/famelung/NorthIndiaSenDT34/ESD/20170302_20170314/IW2/overlap_18.5alks_15rlks.int \nbands = 1 \nwidth = 1673 \nlength = 23 \nscheme = BIP \ndtype = CFLOAT \n'
Arguments: ()
```

For reference, here the output when a job failed (I manually terminated it in this case, normally we see exit code 137):
```
//login4/projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files[1047] cat run_7_geo2rdr_resample_22_20078935.o
Sender: LSF System <lsfadmin@n205>
Subject: Job 20078935: <run_7_geo2rdr_resample_22> in cluster <mk2> Exited

Job <run_7_geo2rdr_resample_22> was submitted from host <n313> by user <famelung> in cluster <mk2>.
Job was executed on host(s) <n205>, in queue <general>, as user <famelung> in cluster <mk2>.
</nethome/famelung> was used as the home directory.
</scratch/projects/insarlab/famelung/NorthIndiaSenDT34/run_files> was used as the working directory.
Started at Sat Mar 30 06:08:45 2019
Results reported on Sat Mar 30 06:16:41 2019

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#! /bin/tcsh
#BSUB -J run_7_geo2rdr_resample_22
#BSUB -P insarlab
#BSUB -n 1
#BSUB -R span[hosts=1]
#BSUB -o run_7_geo2rdr_resample_22_%J.o
#BSUB -e run_7_geo2rdr_resample_22_%J.e
#BSUB -q general
#BSUB -W 7:00
#BSUB -R rusage[mem=5000]
free
cd /projects/scratch/insarlab/famelung/NorthIndiaSenDT34/run_files
SentinelWrapper.py -c /projects/scratch/insarlab/famelung/NorthIndiaSenDT34/configs/config_resamp_20171121


------------------------------------------------------------

TERM_OWNER: job killed by owner.
Exited with exit code 130.

Resource usage summary:

    CPU time :                                   1682.96 sec.
    Max Memory :                                 791 MB
    Average Memory :                             675.81 MB
    Total Requested Memory :                     5000.00 MB
    Delta Memory :                               4209.00 MB
    Max Swap :                                   2652 MB
    Max Processes :                              4
    Max Threads :                                20
```
