### ISSUE TITLE
Move orbit files to SENTINEL_ORBITS

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#206]
Currently missing orbits are downloaded in the `/orbits' folder. It would be good to add a script/function that copies or moves them to SENTINEL_ORBITS directory. This probably should be done after `create_runfiles` step, as this is where the orbits are downloaded. Else we modify topsStack so that the orbit files are directly downloaded into SENTINEL_ORBITS.

**Comment by falkamelung** [comment]
Emre tells me that orbits can be downloaded using 

`dloadOrbits.py --dir $SENTINEL_ORBITS`

It works but I get lots of errors (see below).  Is that for the time for which there no precise orbits? I did not investigate.

```
/nethome/swdowinski/heresh/sentinelstack/dloadOrbits.py --start 2019-06-01
Checking orbits of S1A ...
Traceback (most recent call last):
  File "/nethome/swdowinski/heresh/sentinelstack/dloadOrbits.py", line 206, in <module>
    check_download(inps, 'S1A')
  File "/nethome/swdowinski/heresh/sentinelstack/dloadOrbits.py", line 175, in check_download
    tstart = datetime.datetime.strptime(inps.start, fmt)
  File "/nethome/famelung/test/development/rsmas_insar/3rdparty/miniconda3/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/nethome/famelung/test/development/rsmas_insar/3rdparty/miniconda3/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2019-06-01' does not match format '%Y%m%d'
//login4/nethome/swdowinski/S1orbits[1018] /nethome/swdowinski/heresh/sentinelstack/dloadOrbits.py --start 20190601
Checking orbits of S1A ...
Number of days to check:  66
Searching for 2019-06-01 12:00:00
Searching for 2019-06-02 12:00:00
Searching for 2019-06-03 12:00:00
Searching for 2019-06-04 12:00:00
Searching for 2019-06-05 12:00:00
Searching for 2019-06-06 12:00:00
Searching for 2019-06-07 12:00:00
Searching for 2019-06-08 12:00:00
Searching for 2019-06-09 12:00:00
Searching for 2019-06-10 12:00:00
Searching for 2019-06-11 12:00:00
Searching for 2019-06-12 12:00:00
Searching for 2019-06-13 12:00:00
Searching for 2019-06-14 12:00:00
Searching for 2019-06-15 12:00:00
Searching for 2019-06-16 12:00:00
Searching for 2019-06-17 12:00:00
Searching for 2019-06-18 12:00:00
Searching for 2019-06-19 12:00:00
Searching for 2019-06-20 12:00:00
Searching for 2019-06-21 12:00:00
Searching for 2019-06-22 12:00:00
Searching for 2019-06-23 12:00:00
Searching for 2019-06-24 12:00:00
Searching for 2019-06-25 12:00:00
Searching for 2019-06-26 12:00:00
Searching for 2019-06-27 12:00:00
Searching for 2019-06-28 12:00:00
Searching for 2019-06-29 12:00:00
Searching for 2019-06-30 12:00:00
Searching for 2019-07-01 12:00:00
Searching for 2019-07-02 12:00:00
Searching for 2019-07-03 12:00:00
Searching for 2019-07-04 12:00:00
Searching for 2019-07-05 12:00:00
Searching for 2019-07-06 12:00:00
Searching for 2019-07-07 12:00:00
Searching for 2019-07-08 12:00:00
Searching for 2019-07-09 12:00:00
Searching for 2019-07-10 12:00:00
Searching for 2019-07-11 12:00:00
Searching for 2019-07-12 12:00:00
Searching for 2019-07-13 12:00:00
Searching for 2019-07-14 12:00:00
Searching for 2019-07-15 12:00:00
Searching for 2019-07-16 12:00:00
Searching for 2019-07-17 12:00:00
Failed to find orbits for tref 2019-07-17 12:00:00
Searching for 2019-07-18 12:00:00
Failed to find orbits for tref 2019-07-18 12:00:00
Searching for 2019-07-19 12:00:00
Failed to find orbits for tref 2019-07-19 12:00:00
Searching for 2019-07-20 12:00:00
Failed to find orbits for tref 2019-07-20 12:00:00
Searching for 2019-07-21 12:00:00
Failed to find orbits for tref 2019-07-21 12:00:00
Searching for 2019-07-22 12:00:00
Failed to find orbits for tref 2019-07-22 12:00:00
Searching for 2019-07-23 12:00:00
Failed to find orbits for tref 2019-07-23 12:00:00
Searching for 2019-07-24 12:00:00
Failed to find orbits for tref 2019-07-24 12:00:00
```
