### ISSUE TITLE
process_rsmas.py -H bug

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#240]
I am getting the error message below. It will be good if the `MinSAR_template.cfg` will be displayed, but this is probably what you had in mind.
```
//login4/nethome/famelung[1005] process_rsmas.py -H
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce

*************** Template Options ****************
Custom Template File:  None
Project Name:  None
Work Dir:  /nethome/famelung
Traceback (most recent call last):
  File "/nethome/famelung/test/development/rsmas_insar/minsar/process_rsmas.py", line 269, in <module>
    main()
  File "/nethome/famelung/test/development/rsmas_insar/minsar/process_rsmas.py", line 59, in main
    inps = process_rsmas_cmd_line_parse(iargs)
  File "/nethome/famelung/test/development/rsmas_insar/minsar/process_rsmas.py", line 50, in process_rsmas_cmd_line_parse
    inps = putils.create_or_update_template(inps)
  File "/nethome/famelung/test/development/rsmas_insar/minsar/utils/process_utilities.py", line 231, in create_or_update_template
    inps = create_default_template(inps)
  File "/nethome/famelung/test/development/rsmas_insar/minsar/utils/process_utilities.py", line 247, in create_default_template
    inps.customTemplateFile = os.path.abspath(inps.customTemplateFile)
  File "/nethome/famelung/test/development/rsmas_insar/3rdparty/miniconda3/lib/python3.7/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by mirzaees** [comment]
fixed
