### ISSUE TITLE
troubleshooting ISCE on pegasus: File exists error

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#276]
I occasionally get a File exists error in the last processing step. I then ran 'bsub < run_8_merge_master_slave_slc_5.job` and it worked fine. For `NESD` option it happens in the last processing step as well. There should be an easy way in ice to fix this (I found that at some time but did not know who to commit to ice at the time).

```
//login3/projects/scratch/insarlab/famelung/BolnaySenDT150[1030] cat run_files/run_8_merge_master_slave_slc_5_23142828.e
Traceback (most recent call last):
  File "/nethome/famelung/test/development_fork/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/nethome/famelung/test/development_fork/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/nethome/famelung/test/development_fork/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/nethome/famelung/test/development_fork/rsmas_insar/sources/isceStack/topsStack/mergeBursts.py", line 394, in main
    os.makedirs(mergedir)
  File "/nethome/famelung/test/development_fork/rsmas_insar/3rdparty/miniconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/projects/scratch/insarlab/famelung/BolnaySenDT150/merged/geom_master'
```

Here is another incidence where the error occurs (NESD switched off). It turns out to be exactly the same error.
```
//login4/projects/scratch/insarlab/famelung/BolnaySenDT77[1049] cat /projects/scratch/insarlab/famelung/BolnaySenDT77/run_files/run_8_merge_master_slave_slc_4_23148794.e
Traceback (most recent call last):
  File "/nethome/famelung/test/development_fork/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/nethome/famelung/test/development_fork/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/nethome/famelung/test/development_fork/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/nethome/famelung/test/development_fork/rsmas_insar/sources/isceStack/topsStack/mergeBursts.py", line 394, in main
    os.makedirs(mergedir)
  File "/nethome/famelung/test/development_fork/rsmas_insar/3rdparty/miniconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/projects/scratch/insarlab/famelung/BolnaySenDT77/merged/geom_master'
```

**Comment by falkamelung** [comment]
The original code in `mergeBursts.py` is:
```
392     mergedir = os.path.dirname(inps.outfile)
393     if not os.path.isdir(mergedir):dd
394         os.makedirs(mergedir)
```
I think the error occurs when there is a race condition. So, following
I am trying:
```
import pathlib
mergedir = os.path.dirname(inps.outfile)
pathlib.Path(mergedir).mkdir(parents=True, exist_ok=True)
```
