### ISSUE TITLE
Weird Stampede logging error

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#325]
I got the error below. Have you seen this? We get the Warning message frequently and I am not concerned about. The isce.log* files the code is complaining about exist
```
//login3/scratch/05861/tg851601/BalotschistanSenAT115/run_files[1031] cat run_5_overlap_geo2rdr_resample_5447981.e
using /tmp/launcher.5447981.hostlist.uQie6e58 to get hosts
starting job on c506-102
starting job on c506-123
starting job on c506-124
--- Logging error ---
Traceback (most recent call last):
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 167, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/BalotschistanSenAT115/run_files/isce.log.4' -> '/scratch/05861/tg851601/BalotschistanSenAT115/run_files/isce.log.5'
Call stack:
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/resamp_withCarrier.py", line 237, in main
    outimg = resampSlave(botBurst, slvBurst, rdict, outname, (not inps.noflat))
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/resamp_withCarrier.py", line 95, in resampSlave
    rObj.resamp_slc(imageOut=imgOut)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/stdproc/stdproc/resamp_slc/Resamp_slc.py", line 75, in resamp_slc
    self.setDefaults()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/stdproc/stdproc/resamp_slc/Resamp_slc.py", line 182, in setDefaults
    self.logger.warning('The variable INPUT_LINES has been set to the default value %d which is the number of lines in the slc image.' % (self.inputLines))
Message: 'The variable INPUT_LINES has been set to the default value 1504 which is the number of lines in the slc image.'
Arguments: ()


//login3/scratch/05861/tg851601/BalotschistanSenAT115/run_files[1034] ll isce*
-rw------- 1 tg851601 G-820134 8088 Mar 29 00:40 isce.log
-rw------- 1 tg851601 G-820134 8088 Mar 29 00:40 isce.log.1
-rw------- 1 tg851601 G-820134 8088 Mar 29 00:40 isce.log.2
-rw------- 1 tg851601 G-820134 9099 Mar 29 00:42 isce.log.3
-rw------- 1 tg851601 G-820134 8088 Mar 29 00:40 isce.log.4
-rw------- 1 tg851601 G-820134 9099 Mar 29 00:42 isce.log.5
```

**Comment by falkamelung** [comment]
Then I ran `sbatch < run_6_*`. It works but I get a similar error. So maybe these are not fatal errors?

```
 head -300 run_6_pairs_misreg_5450280.e
using /tmp/launcher.5450280.hostlist.xgQWUbxS to get hosts
starting job on c502-054
starting job on c502-061
starting job on c505-074
starting job on c505-081
starting job on c505-082
starting job on c505-083
starting job on c505-084
starting job on c505-091
Warning: Permanently added 'c505-091' (ECDSA) to the list of known hosts.
Warning: Permanently added 'c502-054' (ECDSA) to the list of known hosts.
Warning: Permanently added 'c505-082' (ECDSA) to the list of known hosts.
Warning: Permanently added 'c505-081' (ECDSA) to the list of known hosts.
Warning: Permanently added 'c502-061' (ECDSA) to the list of known hosts.
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
--- Logging error ---
Traceback (most recent call last):
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 167, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/BalotschistanSenAT115/run_files/isce.log.4' -> '/scratch/05861/tg851601/BalotschistanSenAT115/run_files/isce.log.5'
Call stack:
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/overlap_withDEM.py", line 360, in main
    multCor = createCoherence(multIntName)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/overlap_withDEM.py", line 224, in createCoherence
    inimg = IML.mmapFromISCE(intfile + '.xml', logging)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 482, in mmapFromISCE
    'dtype = %s \n'%(img.dataType))
Message: 'Creating readonly ISCE mmap with \nfile = /scratch/05861/tg851601/BalotschistanSenAT115/ESD/20160217_20160405/IW3/overlap_11.5alks_15rlks.int \nbands = 1 \nwidth = 1607 \nlength = 23 \nscheme = BIP \ndtype = CFLOAT \n'
Arguments: ()
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
--- Logging error ---
Traceback (most recent call last):
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 166, in doRollover
    os.remove(dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/BalotschistanSenAT115/run_files/isce.log.5'
Call stack:
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/overlap_withDEM.py", line 360, in main
    multCor = createCoherence(multIntName)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/overlap_withDEM.py", line 224, in createCoherence
    inimg = IML.mmapFromISCE(intfile + '.xml', logging)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 482, in mmapFromISCE
    'dtype = %s \n'%(img.dataType))
Message: 'Creating readonly ISCE mmap with \nfile = /scratch/05861/tg851601/BalotschistanSenAT115/ESD/20181004_20181028/IW3/overlap_11.5alks_15rlks.int \nbands = 1 \nwidth = 1607 \nlength = 23 \nscheme = BIP \ndtype = CFLOAT \n'
Arguments: ()
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
--- Logging error ---
Traceback (most recent call last):
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 167, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/BalotschistanSenAT115/run_files/isce.log.4' -> '/scratch/05861/tg851601/BalotschistanSenAT115/run_files/isce.log.5'
Call stack:
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/overlap_withDEM.py", line 360, in main
    multCor = createCoherence(multIntName)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/overlap_withDEM.py", line 224, in createCoherence
    inimg = IML.mmapFromISCE(intfile + '.xml', logging)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 482, in mmapFromISCE
    'dtype = %s \n'%(img.dataType))
Message: 'Creating readonly ISCE mmap with \nfile = /scratch/05861/tg851601/BalotschistanSenAT115/ESD/20180910_20181004/IW3/overlap_12.5alks_15rlks.int \nbands = 1 \nwidth = 1607 \nlength = 22 \nscheme = BIP \ndtype = CFLOAT \n'
Arguments: ()
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateAzimuthMisreg.py:143: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
/home1/05861/tg851601/test/operations/rsmas_insar/sources/isceStack/topsStack/estimateRangeMisreg.py:207: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  hist, bins = np.histogram(val, 50, normed=1)
```

**Comment by falkamelung** [comment]
Unfortunately this logging error still crops up. When I run again it appears for a different run_6_overlap_resample_0_*.e . As I used launcher and tasks are submitted randomly (I think), this may nor may not have been the same tasks.  Need to  switch defaults to eliminate launcher.
```
#########################
#### /scratch/05861/tg851601/HanumangarhSenDT34/run_files/run_6_overlap_resample_0_6.e 
#########################
--- Logging error ---
Traceback (most recent call last):
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 167, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/HanumangarhSenDT34/run_files/isce.log.4' -> '/scratch/05861/tg851601/HanumangarhSenDT34/run_files/isce.log.5'
Call stack:
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/resamp_withCarrier.py", line 236, in main
    outimg = resampSlave(botBurst, slvBurst, rdict, outname, (not inps.noflat))
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/resamp_withCarrier.py", line 95, in resampSlave
    rObj.resamp_slc(imageOut=imgOut)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/stdproc/stdproc/resamp_slc/Resamp_slc.py", line 75, in resamp_slc
    self.setDefaults()
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/stdproc/stdproc/resamp_slc/Resamp_slc.py", line 182, in setDefaults
    self.logger.warning('The variable INPUT_LINES has been set to the default value %d which is the number of lines in the slc image.' % (self.inputLines))
Message: 'The variable INPUT_LINES has been set to the default value 1506 which is the number of lines in the slc image.'
Arguments: ()
```

**Comment by falkamelung** [comment]
The following command gives an logging error
```
SentinelWrapper.py -c /scratch/05861/tg851601/HanumangarhSenDT34/configs/config_misreg_20170101_20170113
Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2', 'Function-3', 'Function-4']
Running: generateIgram
['--master', '/scratch/05861/tg851601/HanumangarhSenDT34/coreg_slaves/20170101', '--slave', '/scratch/05861/tg851601/HanumangarhSenDT34/coreg_slaves/20170113', '--interferogram', '/scratch/05861/tg851601/HanumangarhSenDT34/coarse_interferograms/20170101_20170113', '--interferogram_prefix', 'int', '--overlap']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
minSlave,maxSlave 1 16
minMaster,maxMaster 1 16
minBurst, maxBurst:  1 16
matching burst numbers:  1 1
multiply
read
rdict:  {'rangeOff1': '/scratch/05861/tg851601/HanumangarhSenDT34/coreg_slaves/20170101/overlap/IW1/range_bot_01_02.off', 'rangeOff2': '/scratch/05861/tg851601/HanumangarhSenDT34/coreg_slaves/20170113/overlap/IW1/range_bot_01_02.off', 'azimuthOff': '/scratch/05861/tg851601/HanumangarhSenDT34/coreg_slaves/20170113/overlap/IW1/azimuth_bot_01_02.off'}
multiply
read
matching burst numbers:  2 2
```

```
head -24 run_7_pairs_misreg_0_24.e
--- Logging error ---
Traceback (most recent call last):
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py", line 167, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/HanumangarhSenDT34/run_files/isce.log.3' -> '/scratch/05861/tg851601/HanumangarhSenDT34/run_files/isce.log.4'
Call stack:
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/estimateAzimuthMisreg.py", line 150, in main
    import matplotlib as mpl
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1601, in <module>
    _log.debug('loaded modules: %s', list(sys.modules))
Message: 'loaded modules: %s'
```

**Comment by falkamelung** [comment]
fix committed to ISCE
