### ISSUE TITLE
run_2_unpack_slave_slc failure: Not raising exception for `IOError: [Errno 2]` 

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#349]
Hanumangarh: Sometimes data are missing and  run_2_unpack_slave_slc_1. Why it does not raise exception  if one job fails?

To reproduce error run `ioerrorHanumangarhSenDT34.template` and remove one data set manually and run only `run_2_unpack_slave_slc` 

Action FA: First try without Launcher
```
//login3/scratch/05861/tg851601/HanumangarhSenDT34/run_files[998]  grep IOErr std*run_2*/*
stdout_run_2_unpack_slave_slc/run_2_unpack_slave_slc_1_46.o:IOError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/HanumangarhSenDT34/orbits/20200509/S1A_OPER_AUX_POEORB_OPOD_20200529T120804_V20200508T225942_20200510T005942.EOF'
stdout_run_2_unpack_slave_slc/run_2_unpack_slave_slc_1_46.o:IOError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/HanumangarhSenDT34/orbits/20200509/S1A_OPER_AUX_POEORB_OPOD_20200529T120804_V20200508T225942_20200510T005942.EOF'
stdout_run_2_unpack_slave_slc/run_2_unpack_slave_slc_1_46.o:IOError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/HanumangarhSenDT34/orbits/20200509/S1A_OPER_AUX_POEORB_OPOD_20200529T120804_V20200508T225942_20200510T005942.EOF'
//login3/scratch/05861/tg851601/HanumangarhSenDT34/run_files[999] 
```

```
//c506-001/scratch/05861/tg851601/HanumangarhSenDT34[988] cat out_run_5_overlap_geo2rdr.e 
#########################
#### /scratch/05861/tg851601/HanumangarhSenDT34/run_files/run_5_overlap_geo2rdr_1_5810124.e 
#########################
using /tmp/launcher.5810124.hostlist.TR47q78q to get hosts
starting job on c494-093
#########################
#### /scratch/05861/tg851601/HanumangarhSenDT34/run_files/run_5_overlap_geo2rdr_0_5810123.e 
#########################
using /tmp/launcher.5810123.hostlist.iW5sKUOT to get hosts
starting job on c494-084
Warning: Permanently added 'c494-084' (ECDSA) to the list of known hosts.
#########################
#### /scratch/05861/tg851601/HanumangarhSenDT34/run_files/run_5_overlap_geo2rdr_2_5810125.e 
#########################
using /tmp/launcher.5810125.hostlist.gi5LB4qq to get hosts
starting job on c494-102
#########################
#### /scratch/05861/tg851601/HanumangarhSenDT34/run_files/run_5_overlap_geo2rdr_3_23.e 
#########################
Traceback (most recent call last):
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/geo2rdr.py", line 226, in main
    slave = ut.loadProduct(os.path.join(inps.slave, 'IW{0}.xml'.format(swath)))
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/isceStack/isce2/contrib/stack/topsStack/s1a_isce_utils.py", line 26, in loadProduct
    obj = pm.loadProduct(xmlname)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/iscesys/Component/ProductManager.py", line 25, in loadProduct
    self.load(filename)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/iscesys/Component/Configurable.py", line 1407, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/3rdparty/miniconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/HanumangarhSenDT34/slaves/20200509/IW1.xml'
```

**Comment by falkamelung** [comment]
I tried to reproduce the error by removing a data file. It does not produce the same error but writes an `[Errno 2] No such file or directory`  into the `*.o` instead of the `*.e` file.  Do we need to check in the *.o files for this string?

(action falk: run without launcher)

```ll run_2_unpack_slave_slc_0_2.*
-rw-rw---- 1 tg851601 G-820134    0 Jun  4 07:05 run_2_unpack_slave_slc_0_2.e
-rw-rw---- 1 tg851601 G-820134 1235 Jun  4 07:06 run_2_unpack_slave_slc_0_2.o
```

```
//login3/scratch/05861/tg851601/ioerrorHanumangarhSenDT34/run_files[1106] cat run_2_unpack_slave_slc_0_2.o
Completed Parsing the Configuration file
Functions to be executed:
['Function-1']
Running: Sentinel1_TOPS
['--dirname', '/scratch/05861/tg851601/ioerrorHanumangarhSenDT34/SLC/S1A_IW_SLC__1SDV_20200227T010028_20200227T010055_031431_039E55_26E9.zip /scratch/05861/tg851601/ioerrorHanumangarhSenDT34/SLC/S1A_IW_SLC__1SDV_20200227T010003_20200227T010031_031431_039E55_9497.zip', '--swaths', '2', '--orbitdir', '/work/05861/tg851601/stampede2/insarlab/S1orbits', '--outdir', '/scratch/05861/tg851601/ioerrorHanumangarhSenDT34/slaves/20200227', '--auxdir', '/work/05861/tg851601/stampede2/insarlab/S1aux', '--bbox', '28.0 29.50 73.0 77.1', '--pol', 'vv']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
[Errno 2] No such file or directory: '/scratch/05861/tg851601/ioerrorHanumangarhSenDT34/SLC/S1A_IW_SLC__1SDV_20200227T010003_20200227T010031_031431_039E55_9497.zip'
```
