### ISSUE TITLE
ISCE_STACK confusion between topsStack and stripmapStack

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#368]
I am afraid switching between topsStack and stripmapStack is not working yet. When I run Sentinel data I am getting the error below.  I believe I had particularly problems running `job_submission.py run_0*`. I believe in that case we need to run `exporttopsStack` first but running `exportstripmapStack` and `exporttopsStack` is confusing also. I also had trouble with some strip map stack scripts not found.  Its a mess......

Can't we go back to what we had and just set ISCE_STACK in environment.bash? If your regular login alias is `s.bgood` then we would use `s.bgoods` for stripmapStack. We could have `stripmapStack=True; source setup/environment.bash` and set `ISCE_STACK` depending on `stripmapStack`. How do you think?

```
alias s.bd='export RSMASINSAR_HOME=/work/05861/tg851601/stampede2/test/dev/rsmas_insar; cd $RSMASINSAR_HOME; source ~/accounts/platforms_defaults.bash; source setup/environment.bash; source ~/accounts/alias.bash; source ~/accounts/login_alias.bash; cd -;'
alias s.bds='export RSMASINSAR_HOME=/work/05861/tg851601/stampede2/test/dev/rsmas_insar; stripmapStack=True; cd $RSMASINSAR_HOME; source ~/accounts/platforms_defaults.bash; source setup/environment.bash; source ~/accounts/alias.bash; source ~/accounts/login_alias.bash; cd -;'

```

```
*************** Template Options ****************
Custom Template File:  /work/05861/tg851601/stampede2/test/dev/rsmas_insar/samples/unittestGalapagosSenDT128.template
Project Name:  unittestGalapagosSenDT128
Work Dir:  /scratch/05861/tg851601/unittestGalapagosSenDT128
1-->1
-0.81 -0.80 -90.9 -90.86-->'-0.81 -0.80 -90.9 -90.86'
WARNING: "acquisition_mode" is not given --> default: tops   (available options: tops, stripmap)
auto-->auto
None-->None
1-->1
-0.81 -0.80 -90.9 -90.86-->'-0.81 -0.80 -90.9 -90.86'
template file exists: /scratch/05861/tg851601/unittestGalapagosSenDT128/unittestGalapagosSenDT128.template, no updates
20200629:093629 * execute_runfiles.py /work/05861/tg851601/stampede2/test/dev/rsmas_insar/samples/unittestGalapagosSenDT128.template
20200629:093629 * job_submission.py /scratch/05861/tg851601/unittestGalapagosSenDT128/run_files/run_01_unpack_topo_master --outdir /scratch/05861/tg851601/unittestGalapagosSenDT128/run_files

Working on a SLURM machine ...

Traceback (most recent call last):
  File "/home1/05861/tg851601/test/operations/rsmas_insar/minsar/process_rsmas.py", line 268, in <module>
    main()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/minsar/process_rsmas.py", line 88, in main
    objInsar.run(steps=inps.runSteps)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/minsar/process_rsmas.py", line 246, in run
    self.run_interferogram()
  File "/home1/05861/tg851601/test/operations/rsmas_insar/minsar/process_rsmas.py", line 208, in run_interferogram
    minsar.execute_runfiles.main([self.custom_template_file])
  File "/home1/05861/tg851601/test/operations/rsmas_insar/minsar/execute_runfiles.py", line 73, in main
    job_status = job_obj.submit_batch_jobs(batch_file=item)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/minsar/job_submission.py", line 196, in submit_batch_jobs
    self.get_memory_walltime(batch_file, job_type='batch')
  File "/home1/05861/tg851601/test/operations/rsmas_insar/minsar/job_submission.py", line 468, in get_memory_walltime
    self.num_bursts = putils.get_number_of_bursts(self)
  File "/home1/05861/tg851601/test/operations/rsmas_insar/minsar/utils/process_utilities.py", line 773, in get_number_of_bursts
    from stackSentinel import cmdLineParse as stack_cmd, get_dates
  File "/home1/05861/tg851601/test/operations/rsmas_insar/sources/isce2/contrib/stack/topsStack/stackSentinel.py", line 23, in <module>
    from Stack import config, run, sentinelSLC
ImportError: cannot import name 'sentinelSLC' from 'Stack' (/home1/05861/tg851601/test/operations/rsmas_insar/sources/isce2/contrib/stack/stripmapStack/Stack.py)
```

**Comment by falkamelung** [comment]
solved
