### ISSUE TITLE
Weired MintPy KeyError: 'DATE12'   and  KeyError('ALOOKS')

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#422]
WenchuanSenDT62

This error message appears if there are not all `ll merged/geom_reference/*rdr` files (prep_isce.py also failed because of missing *rsc files). It happened after a run_12*_0 time out (need to test whether rerruning run_12 may cause a problem.)
``` 
Traceback (most recent call last):
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/load_data.py", line 696, in <module>
    main()
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/load_data.py", line 655, in main
    stackObj = read_inps_dict2ifgram_stack_dict_object(inpsDict)
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/load_data.py", line 400, in read_inps_dict2ifgram_stack_dict_object
    date12 = readfile.read_attribute(dsPath)['DATE12'].replace('_','-')
KeyError: 'DATE12'
```

Test whether `prep_isce.py ` works:
```
prep_isce.py -m ../reference/IW1.xml -g ../merged/geom_reference -b ../baselines -d ../merged/interferograms -f filt*.unw

ll merged/interferograms/*/*rsc

```

**Comment by falkamelung** [comment]
Another mintpy error is `Exception: KeyError('ALOOKS')` in `invert_network` step.  It occurred after some other error occurred and I restarted with `submit_jobs.bash --start 7`
```
        5.13897753e+00, -4.30229301e+01,  2.22222481e+01, -2.18162365e+01,                                                                                                                    [372/1984]
       -4.20184669e+01,  1.69025345e+01, -2.70367928e+01, -1.81994610e+01,                                                                                                                              
        4.65129929e+01,  8.74611378e+00, -1.35070300e+00,  2.43195953e+01,                                                                                                                              
       -5.02499809e+01, -4.14795609e+01,  4.07213516e+01,  5.09909096e+01,                                                                                                                              
       -3.50911293e+01,  8.46908493e+01,  9.49832382e+01,  4.76291161e+01                                                                                                                               
Exception: KeyError('ALOOKS')                                                                                                                                                                           
                                                                                                                                                                                                        
distributed.worker - WARNING -  Compute Failed                                                                                                                                                          
Function:  ifgram_inversion_patch                                                                                                                                                                       
args:      ()                                                                                                                                                                                           
kwargs:    {'ifgram_file': '/scratch/05861/tg851601/WenchuanSenAT128/mintpy/inputs/ifgramStack.h5', 'ref_phase': array([-4.06390800e+01, -1.14269600e+02, -9.38251343e+01,  1.24657736e+01,             
       -1.23777985e+02, -3.42483177e+01,  8.47234879e+01, -1.89769516e+01,                                                                                                                              
        7.69995422e+01,  5.14705849e+01,  2.31546383e+01, -1.71454391e+01,                                                                                                                              
        1.12715050e+02,  8.94022751e+00,  8.95709395e-02,  2.57326674e+00,                                                                                                                              
       -4.70377541e+01, -4.34989052e+01, -2.84456940e+01, -2.95052891e+01,                                                                                                                              
       -4.65071754e+01, -1.26543865e+01, -7.49055052e+00, -4.33187599e+01,                                                                                                                              
        2.76172142e+01,  2.00434399e+01, -9.25770760e+00,  1.82060623e+01,                                                                                                                              
        5.13897753e+00, -4.30229301e+01,  2.22222481e+01, -2.18162365e+01,                                                                                                                              
       -4.20184669e+01,  1.69025345e+01, -2.70367928e+01, -1.81994610e+01,                                                                                                                              
        4.65129929e+01,  8.74611378e+00, -1.35070300e+00,  2.43195953e+01,                                                                                                                              
       -5.02499809e+01, -4.14795609e+01,  4.07213516e+01,  5.09909096e+01,                                                                                                                              
       -3.50911293e+01,  8.46908493e+01,  9.49832382e+01,  4.76291161e+01                                                                                                                               
Exception: KeyError('ALOOKS')                                                                                                                                                                           
                                                                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                      
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 1119, in <module>                                                                                     
    main()                                                                                                                                                                                              
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 1109, in main                                                                                         
    app.run(steps=inps.runSteps, plot=inps.plot)                                                                                                                                                        
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 1053, in run                                                                                          
    self.run_network_inversion(sname)                                                                                                                                                                   
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 580, in run_network_inversion                                                                         
    mintpy.ifgram_inversion.main(iargs)                                                                                                                                                                 
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 1142, in main                                                                                         
    ifgram_inversion(inps)                                                                                                                                                                              
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 1078, in ifgram_inversion                                                                             
    results=[ts, temp_coh, num_inv_ifg])                                                                                                                                                                
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/objects/cluster.py", line 147, in run                                                                                            
    return self.collect_result(futures, results, box, submission_time)                                                                                                                                  
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/objects/cluster.py", line 194, in collect_result                                                                                 
    for future, sub_results in as_completed(futures, with_results=True):                                                                                                                                
  File "/scratch/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/distributed/client.py", line 4464, in __next__                                                         
    return self._get_and_raise()                                                                                                                                                                        
  File "/scratch/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/distributed/client.py", line 4455, in _get_and_raise                                                   
    raise exc.with_traceback(tb)                                                                                                                                                                        
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 766, in ifgram_inversion_patch                                                                        
    chunk_size=100000)                                                                                                                                                                                  
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 658, in calc_weight                                                                                   
    L = int(stack_obj.metadata['ALOOKS']) * int(stack_obj.metadata['RLOOKS'])                                                                                                                           
KeyError: 'ALOOKS'    
```
