### ISSUE TITLE
topsStack coveragebug: different number of bursts than the reference

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#436]
Supersite_WenchuanSenDT62

run_12 gives an error

cat out_run_12_merge_reference_secondary_slc.e
```
ValueError: /scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20201019 has different number of bursts (29) than the reference (30)
#########################
#### /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20201031_17.e 
#########################
Traceback (most recent call last):
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/mergeBursts.py", line 369, in main
    inps.reference, ifg.numberOfBursts, reference.numberOfBursts))
ValueError: /scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20201031 has different number of bursts (29) than the reference (30)
#########################
#### /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_error_matches.e 
#########################
Error: "Error" found in /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20200913_10.e
Error: "Traceback" found in /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20200913_10.e
Error: "Error" found in /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20200925_12.e
Error: "Traceback" found in /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20200925_12.e
Error: "Error" found in /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20201019_15.e
Error: "Traceback" found in /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20201019_15.e
Error: "Error" found in /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20201031_17.e
Error: "Traceback" found in /scratch/05861/tg851601/Supersite_WenchuanSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20201031_17.e
```

There are indeed different number of bursts

```
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1034] ll 20200907/IW*/range*off | wc -l
90
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1035] ll 20200913/IW*/range*off | wc -l
89
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1036] ll 20200919/IW*/range*off | wc -l
90
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1037] ll 20200925/IW*/range*off | wc -l
89
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1038] ll 20201001/IW*/range*off | wc -l
90
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1039] ll 20201013/IW*/range*off | wc -l
90
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1040] ll 20201019/IW*/range*off | wc -l
89
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1041] ll 20201025/IW*/range*off | wc -l
90
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1042] ll 20201031/IW*/range*off | wc -l
89
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1043] ll 20201106/IW*/range*off | wc -l
90
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1044] ll 20201112/IW*/range*off | wc -l
90
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys[1045] ll 20201118/IW*/range*off | wc -l
90
```

The difference is for subswath 2:

```
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20200925[1063] ll IW1*/range*off | wc -l
30
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20200925[1064] ll IW2*/range*off | wc -l
29
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20200925[1065] ll IW3*/range*off | wc -l
30

//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20201001[1070] cd ../20201019
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20201019[1071] ll IW1*/range*off | wc -l
30
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20201019[1072] 
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20201019[1072] ll IW2*/range*off | wc -l
29
//login3/scratch/05861/tg851601/Supersite_WenchuanSenDT62/coreg_secondarys/20201019[1073] ll IW3*/range*off | wc -l
30

```

There is an offset in the coverage of the bad ones (starting at 27.44)
```
topsStack.boundingBox               = 28.2 32.8 100.0 110.0      # '-1 0.15 -91.6 -90.9'                           
```
```
Number of SAFE files to be used (cover BBOX): 56
*****************************************
Number of dates : 14
List of dates :
['20200826', '20200901', '20200907', '20200913', '20200919', '20200925', '20201001', '20201013', '20201019', '20201025', '20201031', '20201106', '20201112', '20201118']
date      south      north
20200826 26.880167 33.45649
20200901 27.442366 33.953007
20200907 26.880192 33.456238
20200913 27.442238 33.953011
20200919 26.880573 33.456345
20200925 27.441908 33.953033
20201001 26.880476 33.456615
20201013 26.880518 33.456669
20201019 27.107538 33.621044
20201025 26.880894 33.456932
20201031 27.10741 33.621506
20201106 26.880932 33.456711
20201112 27.107689 33.621311
20201118 26.880466 33.45649
*****************************************
The overlap region among all dates (based on the preview kml files):
 South   North   East  West
27.442366 33.456238 101.776634 105.534843
*****************************************
All dates (14)
['20200826', '20200901', '20200907', '20200913', '20200919', '20200925', '20201001', '20201013', '20201019', '20201025', '20201031', '20201106', '20201112', '20201118']

dates covering the bbox (14)
['20200826', '20200901', '20200907', '20200913', '20200919', '20200925', '20201001', '20201013', '20201019', '20201025', '20201031', '20201106', '20201112', '20201118']

The reference date was not chosen. The first date is considered as reference date.

All SLCs will be coregistered to : 20200826
secondary dates :
['20200901', '20200907', '20200913', '20200919', '20200925', '20201001', '20201013', '20201019', '20201025', '20201031', '20201106', '20201112', '20201118']

No existing stack was identified. A new stack will be generated.
```

NorthAnatoliaSenAT87 wil all images (starting in 2014)
```
NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150316_19.e
Traceback (most recent call last):
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/mergeBursts.py", line 369, in main
    inps.reference, ifg.numberOfBursts, reference.numberOfBursts))
ValueError: /scratch/05861/tg851601/NorthAnatoliaSenAT87/coreg_secondarys/20150316 has different number of bursts (39) than the reference (40)
```
```
/login3/scratch/05861/tg851601/NorthAnatoliaSenAT87[1043] head -50 q
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150316_19.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150328_20.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150409_21.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150421_22.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150503_23.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150515_24.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150527_25.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150608_26.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150702_27.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150714_28.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150726_29.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150807_30.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150819_31.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20150912_32.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20151030_33.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20151111_34.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20151123_35.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20151205_36.e
Error: "Traceback" found in /scratch/05861/tg851601/NorthAnatoliaSenAT87/run_files/run_12_merge_reference_secondary_slc_0_20151217_37.e
```

**Comment by falkamelung** [comment]
coveragebug_SinabungSenDT62

This is an easy test case. Just requires 21 images and few bursts. It gives the message `has different number of bursts (4) than the reference (6)`

```
//login3/scratch/05861/tg851601/coveragebug_SinabungSenDT62[1017] ls -1 secondarys/
20180509
20180515
20180521
20180602
20180608
20180614
20180620
20180626
20180702
20180708
20180714
20180720
20180726
20180801
20180807
20180813
20180819
20180831
20180906
20180912
```

```
Number of dates : 21
List of dates :
['20180503', '20180509', '20180515', '20180521', '20180602', '20180608', '20180614', '20180620', '20180626', '20180702', '20180708', '20180714', '20180720', '20180726', '20180801', '20180807', '20180813', '20180819', '20180831', '20180906', '20180912']
date      south      north
20180503 1.977394 4.242988
20180509 1.198097 4.796553
20180515 1.976694 4.243026
20180521 1.198008 4.797219
20180602 1.197768 4.796978
20180608 2.642555 4.241265
20180614 1.19752 4.796324
20180620 2.642732 4.241537
20180626 1.196976 4.796412
20180702 2.642894 4.241211
20180708 1.197102 4.797167
20180714 2.642616 4.241396
20180720 1.196424 4.796523
20180726 2.642779 4.240966
20180801 1.197473 4.796195
20180807 1.976535 4.242635
20180813 1.19787 4.796314
20180819 1.976896 4.242526
20180831 1.977472 4.242084
20180906 1.197972 4.795808
20180912 1.976351 4.242071
*****************************************
The overlap region among all dates (based on the preview kml files):
 South   North   East  West
2.642894 4.240966 96.947037 99.383072
*****************************************
All dates (21)
['20180503', '20180509', '20180515', '20180521', '20180602', '20180608', '20180614', '20180620', '20180626', '20180702', '20180708', '20180714', '20180720', '20180726', '20180801', '20180807', '20180813', '20180819', '20180831', '20180906', '20180912']

dates covering the bbox (21)
['20180503', '20180509', '20180515', '20180521', '20180602', '20180608', '20180614', '20180620', '20180626', '20180702', '20180708', '20180714', '20180720', '20180726', '20180801', '20180807', '20180813', '20180819', '20180831', '20180906', '20180912']

The reference date was not chosen. The first date is considered as reference date.

All SLCs will be coregistered to : 20180503
secondary dates :
['20180509', '20180515', '20180521', '20180602', '20180608', '20180614', '20180620', '20180626', '20180702', '20180708', '20180714', '20180720', '20180726', '20180801', '20180807', '20180813', '20180819', '20180831', '20180906', '20180912']
```

```
/scratch/05861/tg851601/coveragebug_SinabungSenDT62/run_files/run_12_merge_reference_secondary_slc_0_20180608_12.e
Traceback (most recent call last):
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/scratch/05861/tg851601/code2/rsmas_insar/sources/isce2/contrib/stack/topsStack/mergeBursts.py", line 369, in main
    inps.reference, ifg.numberOfBursts, reference.numberOfBursts))
ValueError: /scratch/05861/tg851601/coveragebug_SinabungSenDT62/coreg_secondarys/20180608 has different number of bursts (4) than the reference (6)
```
