### ISSUE TITLE
topsStack coveragebug: Could not determine a suitable burst offset ('looks like there are missing frames')

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#447]
coveragebug_KokoxiliBig30SenAT70

an error occurs for 20151029.  Currently it has to be removed using `excludeDates=20151029`.  It is flagged by `stackSentinel.py` as  `dates for which it looks like there are missing frames`

```
cat run_files/run_04_fullBurst_geo2rdr_0_20151029_7.e
Traceback (most recent call last):
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/scratch/05861/tg851601/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/geo2rdr.py", line 249, in main
    burstoffset, minBurst, maxBurst = reference.getCommonBurstLimits(secondary)
  File "/scratch/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 266, in getCommonBurstLimits
    burstoffset = self.getBurstOffset(sFrame)
  File "/scratch/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 228, in getBurstOffset
    return -sframe.getBurstOffset(self)
  File "/scratch/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 258, in getBurstOffset
    raise  Exception('Could not determine a suitable burst offset')
Exception: Could not determine a suitable burst offset
```

```
*****************************************
Number of dates : 11
List of dates :
['20150502', '20150514', '20150526', '20150607', '20150701', '20150725', '20150818', '20150911', '20151005', '20151029', '20151122']
date      south      north
20150502 28.218657 30.137547
20150514 27.939894 31.638449
20150526 28.218006 30.137213
20150607 27.940123 31.638065
20150701 28.609547 32.302635
20150725 28.609661 32.302422
20150818 28.608404 32.301411
20150911 28.608496 32.301739
20151005 27.995829 33.015747
20151029 27.995508 33.015427
20151122 29.164032 32.684528
*****************************************
The overlap region among all dates (based on the preview kml files):
 South   North   East  West
29.164032 30.137213 94.033928 96.732071
*****************************************
All dates (11)
['20150502', '20150514', '20150526', '20150607', '20150701', '20150725', '20150818', '20150911', '20151005', '20151029', '20151122']

dates covering the bbox (9)
['20150514', '20150607', '20150701', '20150725', '20150818', '20150911', '20151005', '20151029', '20151122']

dates for which it looks like there are missing frames
['20151029']
```

**Comment by falkamelung** [comment]
Solved by geopandas
