### ISSUE TITLE
topsStack chunk processing: successes and failures

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#454]
`

**Comment by falkamelung** [comment]
KokoxiliBigChunk40SenDT48 fails in run_06

```
cat run_files/run_06_extract_stack_valid_region_0__1.e
Traceback (most recent call last):
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/extractCommonValidRegion.py", line 141, in <module>
    main()
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/extractCommonValidRegion.py", line 121, in main
    secondaryList = dropSecondarysWithDifferentNumberOfBursts(secondaryList, inps.reference, swathList)
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/extractCommonValidRegion.py", line 78, in dropSecondarysWithDifferentNumberOfBursts
    prodReference = ut.loadProduct(os.path.join(reference, 'IW{0}.xml'.format(swath)))
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/s1a_isce_utils.py", line 26, in loadProduct
    obj = pm.loadProduct(xmlname)
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/iscesys/Component/ProductManager.py", line 25, in loadProduct
    self.load(filename)
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/iscesys/Component/Configurable.py", line 1410, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/work/05861/tg851601/stampede2/test/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
OSError: [Errno 22] Invalid argument: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/stack/IW3.xml'
```
```
cat run_files/run_06_extract_stack_valid_region_0__1.o
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/stack  already exists.
Replacing reference with existing stack.
updating the valid overlap region of:
/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/stack
checking the number of bursts in coreg_secondarys against the one in reference
WARNING: 20160729 has different number of bursts (9) than the reference stack (10) for swath 1 --> exclude it for common region calculation
```

**Comment by falkamelung** [comment]
KokoxiliBigChunk36SenDT48
timed out even after 2 hours. Maybe because of DEM (there were gdal errors). 

wd2KokoxiliBigChunk36SenDT48 worked flawless

**Comment by falkamelung** [comment]
Logging error in run_10.  Running --start 11 works.  Need to check whether skipping "---Loggingerror---" works
```
cat run_10_filter_coherence_error_matches.e
Error: "Error" found in /scratch/05861/tg851601/KokoxiliBigChunk36SenDT48/run_files/run_10_filter_coherence_11_20201130_20201212_40.e
Error: "FileNotFoundError" found in /scratch/05861/tg851601/KokoxiliBigChunk36SenDT48/run_files/run_10_filter_coherence_11_20201130_20201212_40.e
Error: "Traceback" found in /scratch/05861/tg851601/KokoxiliBigChunk36SenDT48/run_files/run_10_filter_coherence_11_20201130_20201212_40.e
Error: "Error" found in /scratch/05861/tg851601/KokoxiliBigChunk36SenDT48/run_files/run_10_filter_coherence_11_20201130_20201212_40.e
Error: "FileNotFoundError" found in /scratch/05861/tg851601/KokoxiliBigChunk36SenDT48/run_files/run_10_filter_coherence_11_20201130_20201212_40.e
Error: "Traceback" found in /scratch/05861/tg851601/KokoxiliBigChunk36SenDT48/run_files/run_10_filter_coherence_11_20201130_20201212_40.e
//login3/scratch/05861/tg851601/KokoxiliBigChunk36SenDT48/run_files_err10_logging[1383] cat run_10_filter_coherence_11_20201130_20201212_40.e
---Loggingerror---
Traceback(mostrecentcalllast):
File"/work/05861/tg851601/stampede2/test/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py",line70,inemit
self.doRollover()
File"/work/05861/tg851601/stampede2/test/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/logging/handlers.py",line166,indoRollover
os.remove(dfn)
FileNotFoundError:[Errno2]Nosuchfileordirectory:'/scratch/05861/tg851601/KokoxiliBigChunk36SenDT48/isce.log.5'
Callstack:
File"/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py",line251,in<module>
main(args.start,args.end)
File"/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py",line242,inmain
cfgParser.runCmd()
File"/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/SentinelWrapper.py",line54,inrunCmd
func_modules.main(self.funcParams[section])
File"/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/FilterAndCoherence.py",line192,inmain
runFilter(inps.infile,inps.filtfile,inps.filterstrength)
File"/work/05861/tg851601/stampede2/test/code/rsmas_insar/sources/isce2/contrib/stack/topsStack/FilterAndCoherence.py",line62,inrunFilter
objFilter.goldsteinWerner(alpha=filterStrength)
File"/work/05861/tg851601/stampede2/test/code/rsmas_insar/3rdparty/miniconda3/lib/python3.7/site-packages/isce/components/mroipac/filter/Filter.py",line82,ingoldsteinWerner
self.logger.debug("width:%s"%(width))
Message:'width:1194'
Arguments:()
```

**Comment by falkamelung** [comment]
KokoxiliBigChunk40SenDT48
```
//login3/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/run_files[1041] greperror
out_run_10_filter_coherence.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160424_20160729/fine.int.xml'
out_run_10_filter_coherence.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160518_20160729/fine.int.xml'
out_run_10_filter_coherence.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160611_20160729/fine.int.xml'
out_run_10_filter_coherence.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160705_20160729/fine.int.xml'
out_run_10_filter_coherence.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160729_20160822/fine.int.xml'
out_run_10_filter_coherence.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160729_20160915/fine.int.xml'
out_run_10_filter_coherence.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160729_20161015/fine.int.xml'
out_run_10_filter_coherence.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160729_20161108/fine.int.xml'
grep: out_*.o: No such file or directory
run_10_filter_coherence_1_20160424_20160729_18.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160424_20160729/fine.int.xml'
run_10_filter_coherence_1_20160518_20160729_21.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160518_20160729/fine.int.xml'
run_10_filter_coherence_1_20160611_20160729_24.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160611_20160729/fine.int.xml'
run_10_filter_coherence_1_20160705_20160729_27.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160705_20160729/fine.int.xml'
run_10_filter_coherence_1_20160729_20160822_31.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160729_20160822/fine.int.xml'
run_10_filter_coherence_1_20160729_20160915_32.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160729_20160915/fine.int.xml'
run_10_filter_coherence_1_20160729_20161015_33.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160729_20161015/fine.int.xml'
run_10_filter_coherence_1_20160729_20161108_34.e:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk40SenDT48/merged/interferograms/20160729_20161108/fine.int.xml'
grep: run_*.o: No such file or directory
```

It turns out that  for `20160729` there is no `IW1/fine_01.int` 
```
ll 20160729_20160915/IW1*
-rw-rw---- 1 tg851601 G-820134 718868 Jan 25 07:57 20160729_20160915/IW1.xml

20160729_20160915/IW1:
total 2127316
-rw-rw---- 1 tg851601 G-820134 259321776 Jan 25 07:57 fine_02.int
-rw-rw---- 1 tg851601 G-820134       384 Jan 25 07:57 fine_02.int.vrt
-rw-rw---- 1 tg851601 G-820134      3817 Jan 25 07:57 fine_02.int.xml
-rw-rw---- 1 tg851601 G-820134 259321776 Jan 25 07:57 fine_03.int
-rw-rw---- 1 tg851601 G-820134       384 Jan 25 07:57 fine_03.int.vrt
-rw-rw---- 1 tg851601 G-820134      3817 Jan 25 07:57 fine_03.int.xml
-rw-rw---- 1 tg851601 G-820134 259321776 Jan 25 07:57 fine_04.int
```
This is because thsi burst does not appear in `coreg_secondarys`:
```
ls -1 coreg_secondarys/20160729/IW1/azimuth_*.off.vrt
coreg_secondarys/20160729/IW1/azimuth_02.off.vrt
coreg_secondarys/20160729/IW1/azimuth_03.off.vrt
coreg_secondarys/20160729/IW1/azimuth_04.off.vrt
coreg_secondarys/20160729/IW1/azimuth_05.off.vrt
coreg_secondarys/20160729/IW1/azimuth_06.off.vrt
coreg_secondarys/20160729/IW1/azimuth_07.off.vrt
coreg_secondarys/20160729/IW1/azimuth_08.off.vrt
coreg_secondarys/20160729/IW1/azimuth_09.off.vrt
coreg_secondarys/20160729/IW1/azimuth_10.off.vrt
```
