### ISSUE TITLE
run_06  extract_stack_valid_region:  fails if /stack directory exist

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#475]
This behaviour could be fixed by adjusting `extract_stack_valid_region.py` or by adding an `rm -r /stack` into the job file
```
cat out_run_06_extract_stack_valid_region.e
#########################
#### /scratch/05861/tg851601/KokoxiliBigChunk31SenAT41/run_files/run_06_extract_stack_valid_region_0_7654025.e 
#########################
slurmstepd: error: *** JOB 7654025 ON c478-043 CANCELLED AT 2021-04-29T09:44:39 DUE TO TIME LIMIT ***
Killed by signal 15.
#########################
#### /scratch/05861/tg851601/KokoxiliBigChunk31SenAT41/run_files/run_06_extract_stack_valid_region_0__1.e 
#########################
Traceback (most recent call last):
  File "/tmp/rsmas_insar/3rdparty/miniconda3/share/isce2/topsStack/extractCommonValidRegion.py", line 141, in <module>
    main()
  File "/tmp/rsmas_insar/3rdparty/miniconda3/share/isce2/topsStack/extractCommonValidRegion.py", line 121, in main
    secondaryList = dropSecondarysWithDifferentNumberOfBursts(secondaryList, inps.reference, swathList)
  File "/tmp/rsmas_insar/3rdparty/miniconda3/share/isce2/topsStack/extractCommonValidRegion.py", line 78, in dropSecondarysWithDifferentNumberOfBursts
    prodReference = ut.loadProduct(os.path.join(reference, 'IW{0}.xml'.format(swath)))
  File "/tmp/rsmas_insar/3rdparty/miniconda3/share/isce2/topsStack/s1a_isce_utils.py", line 26, in loadProduct
    obj = pm.loadProduct(xmlname)
  File "/tmp/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/isce/components/iscesys/Component/ProductManager.py", line 25, in loadProduct
    self.load(filename)
  File "/tmp/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/isce/components/iscesys/Component/Configurable.py", line 1407, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
  File "/tmp/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/tmp/rsmas_insar/3rdparty/miniconda3/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/tmp/rsmas_insar/3rdparty/miniconda3/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/05861/tg851601/KokoxiliBigChunk31SenAT41/stack/IW3.xml'
#########################
#### /scratch/05861/tg851601/KokoxiliBigChunk31SenAT41/run_files/run_06_extract_stack_valid_region_error_matches.e 
#########################
Error: "Error" found in /scratch/05861/tg851601/KokoxiliBigChunk31SenAT41/run_files/run_06_extract_stack_valid_region_0__1.e
Error: "FileNotFoundError" found in /scratch/05861/tg851601/KokoxiliBigChunk31SenAT41/run_files/run_06_extract_stack_valid_region_0__1.e
Error: "Traceback" found in /scratch/05861/tg851601/KokoxiliBigChunk31SenAT41/run_files/run_06_extract_stack_valid_region_0__1.e
//login3/scratch/05861/tg851601/KokoxiliBigChunk31SenAT41[1012] ll stack
total 700
drwxrwx--- 2 tg851601 G-820134   4096 Apr 29 09:40 IW1
-rw-rw---- 1 tg851601 G-820134 370344 Apr 29 09:40 IW1.xml
drwxrwx--- 2 tg851601 G-820134   4096 Apr 29 09:44 IW2
-rw-rw---- 1 tg851601 G-820134 335176 Apr 29 09:44 IW2.xml
```

**Comment by falkamelung** [comment]
I prepended `rm /stack` to the run_file, which solves the issue
