### ISSUE TITLE
conflict computeBaseline.py with intel/19.1.1 module on frontera

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#487]
There in a conflict that occurs when intel/19.1.1 is loaded two or more times on frontera. Loading it once does not cause the problem. After `module purge`  it does not happen. The solution is `module purge` in jobfile prior to isce/launcher commands
```
 module list

Currently Loaded Modules:
  1) intel/19.1.1   3) git/2.24.1      5) python3/3.7.0   7) pmix/3.1.4      9) xalt/2.10.13
  2) impi/19.0.9    4) autotools/1.2   6) cmake/3.20.3    8) hwloc/1.11.12  10) TACC
```
```
computeBaseline.py --help
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
usage: computeBaseline.py [-h] -m REFERENCE -s SECONDARY -b BASELINEFILE

Use polynomial offsets and create burst by burst interferograms

optional arguments:
  -h, --help            show this help message and exit
  -m REFERENCE, --reference REFERENCE
                        Directory with reference acquisition
  -s SECONDARY, --secondary SECONDARY
                        Directory with secondary acquisition
  -b BASELINEFILE, --baseline_file BASELINEFILE
                        An output text file which contains the computed baseline
```
```
module load intel/19.1.1 

computeBaseline.py --help
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Traceback (most recent call last):
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/share/isce2/topsStack/computeBaseline.py", line 12, in <module>
    import s1a_isce_utils as ut
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/share/isce2/topsStack/s1a_isce_utils.py", line 1, in <module>
    from coregSwathSLCProduct import coregSwathSLCProduct
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/share/isce2/topsStack/coregSwathSLCProduct.py", line 4, in <module>
    from isceobj.Sensor.TOPS.TOPSSwathSLCProduct import TOPSSwathSLCProduct
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 6, in <module>
    import numpy as np
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/home1/05861/tg851601/code/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/opt/apps/intel19/python3/3.7.0/bin/python3"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by falkamelung** [comment]
solved by adding 
```
module purge
```
prior to ISCE run in *jobfile
